name: intel
channels:
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py37_0
  - asn1crypto=1.3.0=py37_0
  - astunparse=1.6.3=py_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - cachetools=4.1.0=py_1
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37_2
  - click=7.1.2=py_0
  - cryptography=2.8=py37_0
  - flake8=3.8.3=py_0
  - gast=0.3.3=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icc_rt=2020.1=intel_217
  - idna=2.8=py37_0
  - importlib-metadata=1.6.1=py37_0
  - intel-openmp=2020.1=intel_217
  - intelpython=2020.1=0
  - keras-preprocessing=1.1.0=py_1
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.12.3=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.1.1=py37_0
  - mccabe=0.6.1=py37_1
  - mkl=2020.1=intel_217
  - mkl-service=2.3.0=py37_0
  - mkl_fft=1.1.0=py37ha68da19_0
  - mkl_random=1.1.0=py37ha68da19_0
  - ncurses=6.2=he6710b0_1
  - numpy-base=1.17.5=py37_1
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pip=20.1.1=py37_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.19=py37_1
  - pyflakes=2.2.0=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py37_1
  - pysocks=1.7.0=py37_1
  - python=3.7.7=hcff3b4d_5
  - readline=8.0=h7b6447c_0
  - requests=2.22.0=py37_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scipy=1.5.0=py37h0b6359f_0
  - setuptools=47.3.1=py37_0
  - sqlite=3.32.3=h62c20be_0
  - tbb=2020.2=intel_217
  - tbb4py=2020.2=py37_intel_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=mkl_py37h6e9ce2d_0
  - tensorflow-base=2.2.0=mkl_py37hd506778_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.10=hbc83047_0
  - urllib3=1.25.7=py37_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aiohttp==3.6.2
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==19.3.0
    - autopep8==1.5.4
    - beautifulsoup4==4.9.1
    - blessings==1.7
    - boto3==1.14.39
    - botocore==1.17.39
    - chardet==3.0.4
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - colorful==0.5.4
    - dm-tree==0.1.5
    - docutils==0.15.2
    - filelock==3.0.12
    - future==0.18.2
    - google==2.0.3
    - google-api-core==1.22.1
    - google-auth==1.20.1
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - grpcio==1.30.0
    - gym==0.17.2
    - hiredis==1.1.0
    - jmespath==0.10.0
    - jsonschema==3.2.0
    - lz4==3.1.0
    - msgpack==1.0.0
    - multidict==4.7.6
    - numpy==1.19.0
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.10
    - opencensus-context==0.1.1
    - opencv-contrib-python==4.4.0.44
    - opencv-python==4.2.0.34
    - opencv-python-headless==4.2.0.34
    - pandas==1.0.5
    - pillow==7.1.2
    - prometheus-client==0.8.0
    - protobuf==3.12.2
    - psutil==5.7.2
    - py-spy==0.3.3
    - pyglet==1.5.0
    - pygraphviz==1.6
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - python-graphviz==0.14.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - ray==1.0.1
    - redis==3.4.1
    - s3transfer==0.3.3
    - six==1.15.0
    - soupsieve==2.0.1
    - tabulate==0.8.7
    - tensorboardx==2.0
    - toml==0.10.1
    - torch==1.5.1
    - torchvision==0.6.1
    - yarl==1.4.2
prefix: /home/yeshg/miniconda3/envs/intel

